ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'on_way';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'arrived';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'in_progress';

ALTER TABLE orders ADD COLUMN IF NOT EXISTS on_way_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS arrived_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS started_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP WITH TIME ZONE;
